### ISSUE TITLE
Refactor the Project Structure 

### ISSUE THREAD

**Issue by HarshCasper** [moja-global/contributors_website#7]
**Is your feature request related to a problem? Please describe.**

While browsing through the Code, I found out specific issues with how the Components and Pages are created in the `src` folder but not stacked properly. This makes understanding and scaling the Code difficult as we will be pushing the entire Pages and Components into them, without any qualms. We can possibly better optimize the Code Organization as part of this Project.

**Describe the solution you'd like**

This issue can be fixed with a simple Pull Request, that would reorganize the Code with a better directory structure. After doing some research, trial and error on different ReactJS projects, I found the folder structure that works best for small to intermediate scale projects: 

```
/src
    /assets
    /components
    /contexts
    /lib
    /pages
    /services
    /styles
```

The `src` would contain all of our React Code. The `components` would consist the components that can be shared across multiple pages like `ossComponent.js` or `mainComponent.js`. `pages` would consist of the pages like `contributors.js` and `firstTimersOnlyIssue.js`. Since we are not using custom CSS and third-party APIs, we would not need `styles`, `services` and all.

All of these changes would be non-breaking and would be done just to improve the directory structure at best. 

**Additional context**

It would take me a few hours from assignment to create a fix for the same. Since this would be my first major contribution at Moja Global, I would like to take it up.

cc: @Tlazypanda @shubhamkarande13

**Comment by shubhamkarande13** [comment]
This is great @HarshCasper!

Please go ahead and make a pull request. @Tlazypanda will review it for you!

Keep up the good work!
